rules:
- id: example-rule
  patterns:
  - pattern: ...
  message: Example rule message
  severity: WARNING

  # Additional Semgrep configurations...

# Configuration for saving and sending the results
save_results: semgrep-results.json

post_run:
  - run: |
      import requests

      url = "https://8e3c-91-125-186-58.ngrok-free.app/handlereports"
      files = {'file': open('semgrep-results.json', 'rb')}
      data = {'key': 'b8138f52c16c7462e99e08fb16920a1fb1dddeafdc41ade2896650dcefc4fe82'}
      response = requests.post(url, files=files, data=data)

      if response.status_code != 200:
          print(f"Failed to send results: {response.status_code}")
